name: build
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Go ${{ matrix.go }} build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Test build
        run: make

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    needs: build
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # required for the changelog to work correctly
    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: v0.131.1
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
